packages:
  - docs
  - playground
  - packages/**
  - examples/**
catalog:
  '@antfu/ni': ^25.0.0
  '@antfu/utils': ^9.2.0
  '@xiaohe01/eslint-config': ^1.8.0
  '@xiaohe01/tsconfig': ^1.1.0
  bumpp: ^10.2.0
  eslint: ^9.29.0
  esno: ^4.8.0
  lint-staged: ^16.1.2
  local-pkg: ^1.1.1
  postcss-html: ^1.8.0
  postcss-scss: ^4.0.9
  simple-git-hooks: ^2.13.0
  stylelint: ^16.21.0
  stylelint-config-recess-order: ^7.1.0
  stylelint-order: ^7.0.0
  stylelint-scss: ^6.12.1
  typescript: ~5.7.3
  unbuild: ^3.5.0
  vite: ^6.3.5
  vitest: ^3.2.4
onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
  - unrs-resolver