packages:
  - docs
  - playground
  - packages/**
  - examples/**
catalog:
  '@antfu/ni': ^24.3.0
  '@antfu/utils': ^9.1.0
  '@xiaohe01/eslint-config': ^1.3.1
  '@xiaohe01/tsconfig': ^1.0.4
  bumpp: ^10.1.0
  eslint: ^9.23.0
  esno: ^4.8.0
  lint-staged: ^15.5.0
  local-pkg: ^1.1.1
  postcss-html: ^1.8.0
  postcss-scss: ^4.0.9
  simple-git-hooks: ^2.12.1
  stylelint: ^16.16.0
  stylelint-config-recess-order: ^6.0.0
  stylelint-order: ^6.0.4
  stylelint-scss: ^6.11.1
  typescript: ~5.7.3
  unbuild: ^3.5.0
  vite: ^6.2.2
  vitest: ^3.0.9
onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks