packages:
  - packages/**
catalogs:
  build:
    tsdown: ^0.12.9
    vite: ^7.0.4
  cli:
    bumpp: ^10.2.0
    pncat: ^0.2.6
  dev:
    '@antfu/ni': ^25.0.0
    '@antfu/utils': ^9.2.0
    '@xiaohe01/tsconfig': ^2.0.0
    typescript: ~5.7.3
  lint:
    '@xiaohe01/eslint-config': ^1.10.0
    eslint: ^9.31.0
    lint-staged: ^16.1.2
    simple-git-hooks: ^2.13.0
    stylelint: ^16.21.1
    stylelint-config-recess-order: ^7.1.0
    stylelint-order: ^7.0.0
    stylelint-scss: ^6.12.1
  node:
    local-pkg: ^1.1.1
  script:
    esno: ^4.8.0
  style:
    postcss-html: ^1.8.0
    postcss-scss: ^4.0.9
  test:
    vitest: ^3.2.4
onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks